//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacioli.Language.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pacioli.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abschläge.
        /// </summary>
        public static string allowance {
            get {
                return ResourceManager.GetString("allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abschlagsbasisbetrag.
        /// </summary>
        public static string allowanceChargeBasis {
            get {
                return ResourceManager.GetString("allowanceChargeBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anhang.
        /// </summary>
        public static string attachment {
            get {
                return ResourceManager.GetString("attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Anhänge.
        /// </summary>
        public static string attachmentsNone {
            get {
                return ResourceManager.GetString("attachmentsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Anhänge.
        /// </summary>
        public static string attachmentsTxt {
            get {
                return ResourceManager.GetString("attachmentsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basis.
        /// </summary>
        public static string basis {
            get {
                return ResourceManager.GetString("basis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrechnungszeitraum.
        /// </summary>
        public static string billingPeriod {
            get {
                return ResourceManager.GetString("billingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käufer.
        /// </summary>
        public static string buyer {
            get {
                return ResourceManager.GetString("buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Artikelnr..
        /// </summary>
        public static string buyerAssignedId {
            get {
                return ResourceManager.GetString("buyerAssignedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte.
        /// </summary>
        public static string card {
            get {
                return ResourceManager.GetString("card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuschläge.
        /// </summary>
        public static string charge {
            get {
                return ResourceManager.GetString("charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktdaten Käufer.
        /// </summary>
        public static string contactBuyer {
            get {
                return ResourceManager.GetString("contactBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktdaten Verkäufer.
        /// </summary>
        public static string contactSeller {
            get {
                return ResourceManager.GetString("contactSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Beträge in.
        /// </summary>
        public static string currencyNote {
            get {
                return ResourceManager.GetString("currencyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundennr..
        /// </summary>
        public static string customerNo {
            get {
                return ResourceManager.GetString("customerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferdatum.
        /// </summary>
        public static string deliveryDate {
            get {
                return ResourceManager.GetString("deliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string docDate {
            get {
                return ResourceManager.GetString("docDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fälligkeit.
        /// </summary>
        public static string dueDate {
            get {
                return ResourceManager.GetString("dueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausnahme.
        /// </summary>
        public static string exception {
            get {
                return ResourceManager.GetString("exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefax.
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelpreis (brutto).
        /// </summary>
        public static string grossUnitPrice {
            get {
                return ResourceManager.GetString("grossUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung.
        /// </summary>
        public static string invoice {
            get {
                return ResourceManager.GetString("invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnungsempfänger.
        /// </summary>
        public static string invoicee {
            get {
                return ResourceManager.GetString("invoicee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnungsnr..
        /// </summary>
        public static string invoiceNo {
            get {
                return ResourceManager.GetString("invoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        public static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelpreis (netto).
        /// </summary>
        public static string netUnitPrice {
            get {
                return ResourceManager.GetString("netUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelldatum.
        /// </summary>
        public static string orderDate {
            get {
                return ResourceManager.GetString("orderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellnr..
        /// </summary>
        public static string orderNo {
            get {
                return ResourceManager.GetString("orderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verpackung.
        /// </summary>
        public static string packaging {
            get {
                return ResourceManager.GetString("packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fälliger Betrag.
        /// </summary>
        public static string payableAmount {
            get {
                return ResourceManager.GetString("payableAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsempfänger.
        /// </summary>
        public static string payee {
            get {
                return ResourceManager.GetString("payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsbedingungen.
        /// </summary>
        public static string paymentTerms {
            get {
                return ResourceManager.GetString("paymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos..
        /// </summary>
        public static string pos {
            get {
                return ResourceManager.GetString("pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorauszahlung.
        /// </summary>
        public static string prepaid {
            get {
                return ResourceManager.GetString("prepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projektnr..
        /// </summary>
        public static string projectNo {
            get {
                return ResourceManager.GetString("projectNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenz Vertrag.
        /// </summary>
        public static string refContractdocument {
            get {
                return ResourceManager.GetString("refContractdocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferschein.
        /// </summary>
        public static string refDeliveryNote {
            get {
                return ResourceManager.GetString("refDeliveryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellreferenz.
        /// </summary>
        public static string refOrder {
            get {
                return ResourceManager.GetString("refOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenz Bestelldokument.
        /// </summary>
        public static string refOrderDocument {
            get {
                return ResourceManager.GetString("refOrderDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmerkung.
        /// </summary>
        public static string remark {
            get {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmerkungen.
        /// </summary>
        public static string remarks {
            get {
                return ResourceManager.GetString("remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rundungsbetrag.
        /// </summary>
        public static string roundingAmount {
            get {
                return ResourceManager.GetString("roundingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkäufer.
        /// </summary>
        public static string seller {
            get {
                return ResourceManager.GetString("seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikelnr..
        /// </summary>
        public static string sellerAssignedId {
            get {
                return ResourceManager.GetString("sellerAssignedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPA-Mandat.
        /// </summary>
        public static string sepaMandate {
            get {
                return ResourceManager.GetString("sepaMandate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferung durch.
        /// </summary>
        public static string shipFrom {
            get {
                return ResourceManager.GetString("shipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warenempfänger.
        /// </summary>
        public static string shipTo {
            get {
                return ResourceManager.GetString("shipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        public static string sum {
            get {
                return ResourceManager.GetString("sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summenübersicht.
        /// </summary>
        public static string sumOverview {
            get {
                return ResourceManager.GetString("sumOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuersatz.
        /// </summary>
        public static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuerbetrag.
        /// </summary>
        public static string taxAmount {
            get {
                return ResourceManager.GetString("taxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuerbasis.
        /// </summary>
        public static string taxBasis {
            get {
                return ResourceManager.GetString("taxBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuerart.
        /// </summary>
        public static string taxCategory {
            get {
                return ResourceManager.GetString("taxCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuersummen.
        /// </summary>
        public static string taxSums {
            get {
                return ResourceManager.GetString("taxSums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtsumme.
        /// </summary>
        public static string totalSum {
            get {
                return ResourceManager.GetString("totalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einheit.
        /// </summary>
        public static string unitQuantity {
            get {
                return ResourceManager.GetString("unitQuantity", resourceCulture);
            }
        }
    }
}
