//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacioli.Language.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pacioli.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoinhaber.
        /// </summary>
        public static string accountHolder {
            get {
                return ResourceManager.GetString("accountHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abschläge.
        /// </summary>
        public static string allowance {
            get {
                return ResourceManager.GetString("allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abschlagsbasisbetrag.
        /// </summary>
        public static string allowanceChargeBasis {
            get {
                return ResourceManager.GetString("allowanceChargeBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anhang.
        /// </summary>
        public static string attachment {
            get {
                return ResourceManager.GetString("attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Anhänge.
        /// </summary>
        public static string attachmentsNone {
            get {
                return ResourceManager.GetString("attachmentsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Anhänge.
        /// </summary>
        public static string attachmentsTxt {
            get {
                return ResourceManager.GetString("attachmentsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankverbindung.
        /// </summary>
        public static string bankverbindung {
            get {
                return ResourceManager.GetString("bankverbindung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basis.
        /// </summary>
        public static string basis {
            get {
                return ResourceManager.GetString("basis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrechnungszeitraum.
        /// </summary>
        public static string billingPeriod {
            get {
                return ResourceManager.GetString("billingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empfänger.
        /// </summary>
        public static string buyer {
            get {
                return ResourceManager.GetString("buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Artikelnr..
        /// </summary>
        public static string buyerAssignedId {
            get {
                return ResourceManager.GetString("buyerAssignedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte.
        /// </summary>
        public static string card {
            get {
                return ResourceManager.GetString("card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuschläge.
        /// </summary>
        public static string charge {
            get {
                return ResourceManager.GetString("charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktdaten Käufer.
        /// </summary>
        public static string contactBuyer {
            get {
                return ResourceManager.GetString("contactBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktdaten Verkäufer.
        /// </summary>
        public static string contactSeller {
            get {
                return ResourceManager.GetString("contactSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Beträge in.
        /// </summary>
        public static string currencyNote {
            get {
                return ResourceManager.GetString("currencyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundennr..
        /// </summary>
        public static string customerNo {
            get {
                return ResourceManager.GetString("customerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tage.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferdatum.
        /// </summary>
        public static string deliveryDate {
            get {
                return ResourceManager.GetString("deliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string docDate {
            get {
                return ResourceManager.GetString("docDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fälligkeit.
        /// </summary>
        public static string dueDate {
            get {
                return ResourceManager.GetString("dueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Lesen der Datei {0}: {1}.
        /// </summary>
        public static string errorFileReadMessage {
            get {
                return ResourceManager.GetString("errorFileReadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausnahme.
        /// </summary>
        public static string exception {
            get {
                return ResourceManager.GetString("exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefax.
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelpreis (brutto).
        /// </summary>
        public static string grossUnitPrice {
            get {
                return ResourceManager.GetString("grossUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Dokument stellt den Inhalt einer E-Rechnung dar. Die Originaldatei ist {0}..
        /// </summary>
        public static string infoText1 {
            get {
                return ResourceManager.GetString("infoText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung.
        /// </summary>
        public static string invoice {
            get {
                return ResourceManager.GetString("invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnungsempfänger.
        /// </summary>
        public static string invoicee {
            get {
                return ResourceManager.GetString("invoicee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnungsnr..
        /// </summary>
        public static string invoiceNo {
            get {
                return ResourceManager.GetString("invoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        public static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine neue Version.
        /// </summary>
        public static string msgCurrentAnnounce {
            get {
                return ResourceManager.GetString("msgCurrentAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die aktuellste Version {0} ist installiert.
        /// </summary>
        public static string msgCurrentInfo {
            get {
                return ResourceManager.GetString("msgCurrentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacioli verarbeitet elektronische Rechnungen und transformiert sie in PDF-Dateien.
        ///Version: {0}
        ///Verfügbare Version: {1}
        ///{2}
        ///
        ///Mehr Informationen im Internet: https://github.com/koozala/pacioli.
        /// </summary>
        public static string msgInfoText {
            get {
                return ResourceManager.GetString("msgInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein aktives Dokument.
        /// </summary>
        public static string msgNoActiveDocument {
            get {
                return ResourceManager.GetString("msgNoActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Dokument geladen.
        /// </summary>
        public static string msgNoDocumentLoaded {
            get {
                return ResourceManager.GetString("msgNoDocumentLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Kontaktieren des Servers: {0}.
        /// </summary>
        public static string msgServerErrorText {
            get {
                return ResourceManager.GetString("msgServerErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Pacioli-Version verfügbar.
        /// </summary>
        public static string msgUpdateAnnounce {
            get {
                return ResourceManager.GetString("msgUpdateAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} ist installiert. Eine aktuellere Version {1} von Pacioli ist verfügbar. Update durchführen?.
        /// </summary>
        public static string msgUpdateAsk {
            get {
                return ResourceManager.GetString("msgUpdateAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelpreis (netto).
        /// </summary>
        public static string netUnitPrice {
            get {
                return ResourceManager.GetString("netUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelldatum.
        /// </summary>
        public static string orderDate {
            get {
                return ResourceManager.GetString("orderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellnr..
        /// </summary>
        public static string orderNo {
            get {
                return ResourceManager.GetString("orderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verpackung.
        /// </summary>
        public static string packaging {
            get {
                return ResourceManager.GetString("packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fälliger Betrag.
        /// </summary>
        public static string payableAmount {
            get {
                return ResourceManager.GetString("payableAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsempfänger.
        /// </summary>
        public static string payee {
            get {
                return ResourceManager.GetString("payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsbedingungen.
        /// </summary>
        public static string paymentTerms {
            get {
                return ResourceManager.GetString("paymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos..
        /// </summary>
        public static string pos {
            get {
                return ResourceManager.GetString("pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorauszahlung.
        /// </summary>
        public static string prepaid {
            get {
                return ResourceManager.GetString("prepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projektnr..
        /// </summary>
        public static string projectNo {
            get {
                return ResourceManager.GetString("projectNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenz Vertrag.
        /// </summary>
        public static string refContractdocument {
            get {
                return ResourceManager.GetString("refContractdocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferschein.
        /// </summary>
        public static string refDeliveryNote {
            get {
                return ResourceManager.GetString("refDeliveryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellreferenz.
        /// </summary>
        public static string refOrder {
            get {
                return ResourceManager.GetString("refOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenz Bestelldokument.
        /// </summary>
        public static string refOrderDocument {
            get {
                return ResourceManager.GetString("refOrderDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmerkung.
        /// </summary>
        public static string remark {
            get {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmerkungen.
        /// </summary>
        public static string remarks {
            get {
                return ResourceManager.GetString("remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rundungsbetrag.
        /// </summary>
        public static string roundingAmount {
            get {
                return ResourceManager.GetString("roundingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkäufer.
        /// </summary>
        public static string seller {
            get {
                return ResourceManager.GetString("seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikelnr..
        /// </summary>
        public static string sellerAssignedId {
            get {
                return ResourceManager.GetString("sellerAssignedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPA-Mandat.
        /// </summary>
        public static string sepaMandate {
            get {
                return ResourceManager.GetString("sepaMandate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferung durch.
        /// </summary>
        public static string shipFrom {
            get {
                return ResourceManager.GetString("shipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warenempfänger.
        /// </summary>
        public static string shipTo {
            get {
                return ResourceManager.GetString("shipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        public static string sum {
            get {
                return ResourceManager.GetString("sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summenübersicht.
        /// </summary>
        public static string sumOverview {
            get {
                return ResourceManager.GetString("sumOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuersatz.
        /// </summary>
        public static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuerbetrag.
        /// </summary>
        public static string taxAmount {
            get {
                return ResourceManager.GetString("taxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuerbasis.
        /// </summary>
        public static string taxBasis {
            get {
                return ResourceManager.GetString("taxBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuerart.
        /// </summary>
        public static string taxCategory {
            get {
                return ResourceManager.GetString("taxCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuersummen.
        /// </summary>
        public static string taxSums {
            get {
                return ResourceManager.GetString("taxSums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Rechnung Inhalt.
        /// </summary>
        public static string title_Content {
            get {
                return ResourceManager.GetString("title_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Ansicht.
        /// </summary>
        public static string title_XmlView {
            get {
                return ResourceManager.GetString("title_XmlView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtsumme.
        /// </summary>
        public static string totalSum {
            get {
                return ResourceManager.GetString("totalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuermeldung (Rechnung).
        /// </summary>
        public static string type102 {
            get {
                return ResourceManager.GetString("type102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnungsdatenblatt.
        /// </summary>
        public static string type130 {
            get {
                return ResourceManager.GetString("type130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkürzte Baurechnung.
        /// </summary>
        public static string type202 {
            get {
                return ResourceManager.GetString("type202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorläufige Baurechnung.
        /// </summary>
        public static string type203 {
            get {
                return ResourceManager.GetString("type203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baurechnung.
        /// </summary>
        public static string type204 {
            get {
                return ResourceManager.GetString("type204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwischen-/Abschlagsrechnung.
        /// </summary>
        public static string type211 {
            get {
                return ResourceManager.GetString("type211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlussrechnung.
        /// </summary>
        public static string type218 {
            get {
                return ResourceManager.GetString("type218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung über abgeschlossene Einheiten.
        /// </summary>
        public static string type219 {
            get {
                return ResourceManager.GetString("type219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigengutschrift.
        /// </summary>
        public static string type261 {
            get {
                return ResourceManager.GetString("type261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusammengefasste Gutschrift.
        /// </summary>
        public static string type262 {
            get {
                return ResourceManager.GetString("type262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preisanpassungsrechnung.
        /// </summary>
        public static string type295 {
            get {
                return ResourceManager.GetString("type295", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preisanpassungsgutschrift.
        /// </summary>
        public static string type296 {
            get {
                return ResourceManager.GetString("type296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gutschrift über Rückstellungen.
        /// </summary>
        public static string type308 {
            get {
                return ResourceManager.GetString("type308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proformarechnung.
        /// </summary>
        public static string type325 {
            get {
                return ResourceManager.GetString("type325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilrechnung.
        /// </summary>
        public static string type326 {
            get {
                return ResourceManager.GetString("type326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung mit Lieferschein.
        /// </summary>
        public static string type331 {
            get {
                return ResourceManager.GetString("type331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handelsrechnung.
        /// </summary>
        public static string type380 {
            get {
                return ResourceManager.GetString("type380", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gutschrift.
        /// </summary>
        public static string type381 {
            get {
                return ResourceManager.GetString("type381", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung.
        /// </summary>
        public static string type382 {
            get {
                return ResourceManager.GetString("type382", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belastungsanzeige.
        /// </summary>
        public static string type383 {
            get {
                return ResourceManager.GetString("type383", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnungskorrektur.
        /// </summary>
        public static string type384 {
            get {
                return ResourceManager.GetString("type384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsolidierte Rechnung.
        /// </summary>
        public static string type385 {
            get {
                return ResourceManager.GetString("type385", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorauszahlungsrechnung.
        /// </summary>
        public static string type386 {
            get {
                return ResourceManager.GetString("type386", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mietrechnung.
        /// </summary>
        public static string type387 {
            get {
                return ResourceManager.GetString("type387", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuerrechnung.
        /// </summary>
        public static string type388 {
            get {
                return ResourceManager.GetString("type388", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenrechnung.
        /// </summary>
        public static string type389 {
            get {
                return ResourceManager.GetString("type389", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delkredere-Rechnung.
        /// </summary>
        public static string type390 {
            get {
                return ResourceManager.GetString("type390", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inkasso-Rechnung.
        /// </summary>
        public static string type393 {
            get {
                return ResourceManager.GetString("type393", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leasing-Rechnung.
        /// </summary>
        public static string type394 {
            get {
                return ResourceManager.GetString("type394", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsignationsrechnung.
        /// </summary>
        public static string type395 {
            get {
                return ResourceManager.GetString("type395", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inkasso-Gutschrift.
        /// </summary>
        public static string type396 {
            get {
                return ResourceManager.GetString("type396", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maschinelle Gutschrift.
        /// </summary>
        public static string type420 {
            get {
                return ResourceManager.GetString("type420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belastungsanzeige.
        /// </summary>
        public static string type456 {
            get {
                return ResourceManager.GetString("type456", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno einer Belastung.
        /// </summary>
        public static string type457 {
            get {
                return ResourceManager.GetString("type457", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno einer Gutschrift.
        /// </summary>
        public static string type458 {
            get {
                return ResourceManager.GetString("type458", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnungskorrekt (selbst ausgestellt).
        /// </summary>
        public static string type471 {
            get {
                return ResourceManager.GetString("type471", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inkassorechnungskorrektur.
        /// </summary>
        public static string type472 {
            get {
                return ResourceManager.GetString("type472", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inkassorechnungskorrektur (selbst ausgestellt).
        /// </summary>
        public static string type473 {
            get {
                return ResourceManager.GetString("type473", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Vorauszahlungsrechnung.
        /// </summary>
        public static string type500 {
            get {
                return ResourceManager.GetString("type500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Inkassorechnung.
        /// </summary>
        public static string type501 {
            get {
                return ResourceManager.GetString("type501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Inkassogutschrift.
        /// </summary>
        public static string type502 {
            get {
                return ResourceManager.GetString("type502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigierte Vorausgutschrift.
        /// </summary>
        public static string type503 {
            get {
                return ResourceManager.GetString("type503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenrechnung.
        /// </summary>
        public static string type527 {
            get {
                return ResourceManager.GetString("type527", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speditionsgutschrift.
        /// </summary>
        public static string type532 {
            get {
                return ResourceManager.GetString("type532", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speditionskorrekturrechnung.
        /// </summary>
        public static string type553 {
            get {
                return ResourceManager.GetString("type553", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung des Versicherers.
        /// </summary>
        public static string type575 {
            get {
                return ResourceManager.GetString("type575", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speditionsrechnung.
        /// </summary>
        public static string type623 {
            get {
                return ResourceManager.GetString("type623", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hafenkostenrechnung.
        /// </summary>
        public static string type633 {
            get {
                return ResourceManager.GetString("type633", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsaufforderung (Rechnung).
        /// </summary>
        public static string type71 {
            get {
                return ResourceManager.GetString("type71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnungsinformation.
        /// </summary>
        public static string type751 {
            get {
                return ResourceManager.GetString("type751", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frachtrechnung.
        /// </summary>
        public static string type780 {
            get {
                return ResourceManager.GetString("type780", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung über Waren oder Leistungen.
        /// </summary>
        public static string type80 {
            get {
                return ResourceManager.GetString("type80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gutschrift über Waren oder Leistungen.
        /// </summary>
        public static string type81 {
            get {
                return ResourceManager.GetString("type81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anspruchsanzeige.
        /// </summary>
        public static string type817 {
            get {
                return ResourceManager.GetString("type817", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung über erhobene Dienste.
        /// </summary>
        public static string type82 {
            get {
                return ResourceManager.GetString("type82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gutschrift über Finanzangleichungen.
        /// </summary>
        public static string type83 {
            get {
                return ResourceManager.GetString("type83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung über Finanzangleichungen.
        /// </summary>
        public static string type84 {
            get {
                return ResourceManager.GetString("type84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsulatsfaktura.
        /// </summary>
        public static string type870 {
            get {
                return ResourceManager.GetString("type870", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilbaurechnung.
        /// </summary>
        public static string type875 {
            get {
                return ResourceManager.GetString("type875", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilschlussbaurechnung.
        /// </summary>
        public static string type876 {
            get {
                return ResourceManager.GetString("type876", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlussbaurechnung.
        /// </summary>
        public static string type877 {
            get {
                return ResourceManager.GetString("type877", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einheit.
        /// </summary>
        public static string unitQuantity {
            get {
                return ResourceManager.GetString("unitQuantity", resourceCulture);
            }
        }
    }
}
